/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'olafurj13' at '10/24/14 4:04 PM' with Gradle 2.1
 *
 * @author olafurj13, @date 10/24/14 4:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
